// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Block types determine rendering and execution behavior.
 * Derived from content prefix - NOT stored in the database.
 */
export type BlockType = "text" | "sh" | "ctx" | "output" | "error" | "picker" | "ran" | "daily" | "h1" | "h2" | "h3" | "bullet" | "todo" | "quote" | "search" | "backup" | "info" | "artifact";
