/**
 * render:: door registry — wires catalog to component implementations
 */

import { defineRegistry } from '@json-render/solid';
import { bbsCatalog } from './catalog';
import {
  DocLayout,
  NavBrand,
  NavSection,
  NavItem,
  NavFooter,
  EntryHeader,
  EntryBody,
  Ellipsis,
  TagBar,
  TagChip,
  RefSection,
  RefCard,
  Breadcrumb,
  Stack,
  Text,
  Divider,
  Card,
  Metric,
  Button,
  TextInput,
  TextArea,
  CodeBlock,
  TuiPanel,
  TuiStat,
  BarChart,
  BarItemComponent,
  DataBlock,
  Image,
  ShippedItem,
  WikilinkChip,
  BacklinksFooter,
  PatternCard,
  ArcTimeline,
  MeetingDiff,
  DecisionLog,
  DependencyChain,
  ContextStream,
  ModeTag,
  QuoteBlock,
  TimeEntry,
  StatsBar,
  MetadataHeader,
  CollapsibleSection,
  FilterButtons,
  TabNav,
  TreeView,
  LinkGraph,
  ActivityHeatmap,
  ProvenanceChain,
  RiskMatrix,
  TimelineDiff,
  Section,
  TimelineEvent,
  StatPill,
  GapItem,
  injectBodyStyles,
} from './components';

// Inject styles when registry is imported
injectBodyStyles();

export const { registry, handlers } = defineRegistry(bbsCatalog, {
  components: {
    DocLayout,
    NavBrand,
    NavSection,
    NavItem,
    NavFooter,
    EntryHeader,
    EntryBody,
    Ellipsis,
    TagBar,
    TagChip,
    RefSection,
    RefCard,
    Breadcrumb,
    Stack,
    Text,
    Divider,
    Card,
    Metric,
    Button,
    TextInput,
    TextArea,
    Code: CodeBlock,
    TuiPanel,
    TuiStat,
    BarChart,
    BarItem: BarItemComponent,
    DataBlock,
    Image,
    ShippedItem,
    WikilinkChip,
    BacklinksFooter,
    PatternCard,
    ArcTimeline,
    MeetingDiff,
    DecisionLog,
    DependencyChain,
    ContextStream,
    ModeTag,
    QuoteBlock,
    TimeEntry,
    StatsBar,
    MetadataHeader,
    CollapsibleSection,
    FilterButtons,
    TabNav,
    TreeView,
    LinkGraph,
    ActivityHeatmap,
    ProvenanceChain,
    RiskMatrix,
    TimelineDiff,
    Section,
    TimelineEvent,
    StatPill,
    GapItem,
  },
  actions: {
    navigate: async () => {},
    createChild: async () => {},
    upsertChild: async () => {},
  },
});

export { bbsCatalog };
