// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A :: marker extracted from block content.
 *
 * Examples:
 * - `ctx::` → Marker { marker_type: "ctx", value: None }
 * - `[project::floatty]` → Marker { marker_type: "project", value: Some("floatty") }
 * - `sh::` → Marker { marker_type: "sh", value: None }
 */
export type Marker = { 
/**
 * The marker type: "ctx", "project", "mode", "issue", "sh", "ai", etc.
 */
markerType: string, 
/**
 * Optional value following the marker.
 * For `[project::floatty]`, value is "floatty".
 * For bare `ctx::`, value is None.
 */
value: string | null, };
