// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Marker } from "./Marker";

/**
 * Structured metadata extracted from block content.
 *
 * This is populated by the metadata extraction hook and stored in `block.metadata`.
 * The structure enables:
 * - Efficient marker queries (what blocks have `[project::X]`?)
 * - Backlink tracking (what blocks link to `[[Page]]`?)
 * - Stub detection (referenced but not yet created pages)
 * - Prefix discovery (what blocks start with `scratch::`?)
 */
export type BlockMetadata = { 
/**
 * All :: markers found in this block.
 * Includes both prefix markers (sh::, ai::, ctx::) and tag markers ([project::X]).
 */
markers: Array<Marker>, 
/**
 * [[wikilink]] targets found in this block.
 * For `[[Target|Alias]]`, stores only "Target".
 * For nested `[[outer [[inner]]]]`, stores both "outer [[inner]]" and "inner".
 */
outlinks: Array<string>, 
/**
 * True if this block is a stub (referenced by wikilink but not yet created).
 * Stubs are blocks under pages:: with no real content yet.
 */
isStub: boolean, 
/**
 * Timestamp of last metadata extraction.
 * Used to skip re-extraction if content unchanged.
 */
extractedAt: number | null, 
/**
 * Block prefix extracted from content (e.g., "sh", "ai", "scratch", "random").
 *
 * ANY `word::` pattern at the start of content becomes a prefix.
 * Only REGISTERED prefixes (sh, ai, ctx, etc.) trigger handlers.
 * All prefixes are queryable for discovery (find all `scratch::` blocks).
 */
prefix: string | null, };
