#!/usr/bin/env bash
#
# bundle-desktop-daddy-skill.sh
#
# Produces a Desktop Daddy-ready zip of the floatty-backend skill with the
# ngrok URL + API key BAKED IN. Desktop Daddy runs in a cloud sandbox with
# no access to ~/.floatty/config.toml and no localhost, so the skill's
# usual probe + config-read path can't work there — we need to pin them.
#
# The zip is written to /tmp/ and is NEVER committed. Only this script is
# committed; secrets live in env vars or ~/.floatty/config.toml at build time.
#
# Usage:
#   ./scripts/bundle-desktop-daddy-skill.sh
#   ./scripts/bundle-desktop-daddy-skill.sh --url https://my.ngrok.app --key sk_xxx
#
# Env var overrides (same as flags):
#   FLOATTY_URL_REMOTE  = https://floatty.ngrok.app  (default)
#   FLOATTY_API_KEY     = read from ~/.floatty/config.toml  (default)
#
# Output:
#   /tmp/floatty-backend-desktop-daddy-YYYY-MM-DD-HHMMSS.zip

set -euo pipefail

# ─── Locate repo + skill ──────────────────────────────────────────
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SKILL_SRC="$REPO_ROOT/plugins/floatty-backend/skills/floatty-backend"

if [[ ! -f "$SKILL_SRC/SKILL.md" ]]; then
  echo "✗ skill source not found at $SKILL_SRC" >&2
  exit 1
fi

# ─── Parse flags / env ────────────────────────────────────────────
REMOTE_URL="${FLOATTY_URL_REMOTE:-https://floatty.ngrok.app}"
API_KEY="${FLOATTY_API_KEY:-}"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --url)  REMOTE_URL="$2"; shift 2 ;;
    --key)  API_KEY="$2"; shift 2 ;;
    -h|--help)
      grep '^#' "${BASH_SOURCE[0]}" | sed 's/^# //;s/^#//'
      exit 0
      ;;
    *)
      echo "✗ unknown arg: $1" >&2
      exit 2
      ;;
  esac
done

# Pull API key from config.toml if not supplied
if [[ -z "$API_KEY" ]]; then
  for cfg in ~/.floatty/config.toml ~/.floatty-dev/config.toml; do
    if [[ -f "$cfg" ]]; then
      API_KEY=$(grep -E '^\s*api_key\s*=' "$cfg" | grep -v anthropic | head -1 | cut -d'"' -f2)
      [[ -n "$API_KEY" ]] && break
    fi
  done
fi

if [[ -z "$API_KEY" ]]; then
  echo "✗ no API key — set FLOATTY_API_KEY, pass --key, or configure ~/.floatty/config.toml" >&2
  exit 1
fi

# ─── Stage skill in a temp dir ────────────────────────────────────
STAGING=$(mktemp -d -t floatty-desktop-daddy-XXXXXX)
trap 'rm -rf "$STAGING"' EXIT

echo "→ staging skill at $STAGING"
cp -r "$SKILL_SRC"/* "$STAGING/"

# ─── Patch floatty-api.sh with pinned credentials ─────────────────
# Inject FLOATTY_URL + FLOATTY_API_KEY at the TOP of the script so the
# probe logic (looking for localhost) is short-circuited. The original
# code then runs against the pinned values.
API_SH="$STAGING/scripts/floatty-api.sh"

{
  echo '#!/usr/bin/env bash'
  echo '# floatty-api.sh — Desktop Daddy build (ngrok URL + API key pinned)'
  echo '# Generated by scripts/bundle-desktop-daddy-skill.sh on '"$(date +%Y-%m-%d)"
  echo '# DO NOT commit this variant — it contains credentials.'
  echo ''
  echo "export FLOATTY_URL='$REMOTE_URL'"
  echo "export FLOATTY_API_KEY='$API_KEY'"
  echo ''
  # Append original file minus its shebang line
  tail -n +2 "$SKILL_SRC/scripts/floatty-api.sh"
} > "$API_SH"
chmod +x "$API_SH"

# Sanity: does the patched script parse?
bash -n "$API_SH" || { echo "✗ patched floatty-api.sh has syntax errors" >&2; exit 1; }

# ─── Zip it ──────────────────────────────────────────────────────
STAMP=$(date +%Y-%m-%d-%H%M%S)
OUT="/tmp/floatty-backend-desktop-daddy-${STAMP}.zip"

(cd "$STAGING" && zip -qr "$OUT" . -x "*.DS_Store" "*.pyc" "__pycache__/*")

SIZE=$(du -h "$OUT" | cut -f1)

# ─── Receipt ──────────────────────────────────────────────────────
echo ""
echo "╭─ Desktop Daddy skill bundle ─────────────────╮"
echo "│  $OUT"
echo "│  size: $SIZE"
echo "│  pinned URL: $REMOTE_URL"
echo "│  pinned key: ${API_KEY:0:12}... (${#API_KEY} chars)"
echo "╰──────────────────────────────────────────────╯"
echo ""
echo "Upload to claude.ai desktop:"
echo "  1. Settings → Skills → Upload skill"
echo "  2. Select $OUT"
echo "  3. Skill name will be 'floatty-backend' (from SKILL.md frontmatter)"
echo ""
echo "Verify from Desktop Daddy:"
echo '  source /mnt/skills/user/floatty-backend/scripts/floatty-api.sh'
echo '  floatty_health'
echo "  # → { version, gitSha, ... }"
